repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.1.0
    hooks:
      - id: tofu_checkov
      - id: tofu_validate
      - id: tofu_fmt
      - id: tofu_tflint
      - id: tofu_trivy
      - id: tofu_docs
        args:
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--recursive=true
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
